#!/bin/bash
#
# Startup script for beholder
# 
# chkconfig: 345 80 10
# description: Beholder whatsapp sensor manager
# processname: beholder
# pidfile: /var/run/yowsup/beholder.pid
# source function library

######################################
# CONFIGURATION
######################################

EXEC=/usr/local/bin/beholder
CONFIG_FILE=/etc/yowsup.config
PID_FILE=/var/run/yowsup/beholder.pid
WAIT_BEFORE_KILL=30

######################################
# START OF THE SCRIPT
######################################

start()
{
	echo "Starting beholder whatsapp sensor manager..."
	echo "--------------------------------------------"
	/usr/bin/python ${EXEC} run -c ${CONFIG_FILE}
	echo ""
}

stop()
{
	echo "Stopping beholder whatsapp sensor manager..."
	echo "--------------------------------------------"
	forceStop;
	echo ""
}

forceStop() 
{
   SLEEP=$WAIT_BEFORE_KILL
   if [ -r "$PID_FILE" ]; then
	echo "Waiting for process: " `cat $PID_FILE`
	while [ $SLEEP -gt 0 ]; do
		sleep 1;
		SLEEP=`expr $SLEEP - 1 `
		
		if [ ! -r "$PID_FILE" ]; then
			echo "Process exited normally."
			break;
		fi
		
		if [ $SLEEP -eq 0 ]; then
			kill -9 `cat $PID_FILE` 2>/dev/null
			rm -f ${PID_FILE} 
			echo "Process killed."
		fi
	done
   fi
}

      
case $1 in  
   start)  
	start
	;;   
   stop)     
	stop
	;;   
   restart)  
	stop
	start
	;;   
   *)
	echo "Unknown option: $1"
	;;
esac   

exit 0  

